[package]
name = "a-workspace"
version = "0.1.0"
edition = "2018"

[workspace]
members = ["src-tauri"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
